### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by richard-voss** [mangecoeur/document-outline#17]
[steps to reproduce:]

1. open "large" (22K) latex document (cannot share, IP), article with quite a few sections, subsections, subsubsections...
2. toggle document outline - used to work before last update with the same document

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [document-outline](https://github.com/mangecoeur/document-outline) package 1.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/richard/.atom/packages/document-outline/lib/abstract-model.js:121

TypeError: Cannot read property 'length' of undefined
    at LatexModel._parseLevel (/packages/document-outline/lib/abstract-model.js:121:82)
    at LatexModel.parse (/packages/document-outline/lib/abstract-model.js:48:17)
    at Object.show (/packages/document-outline/lib/document-outline.js:127:70)
    at Object.updateCurrentEditor (/packages/document-outline/lib/document-outline.js:115:12)
    at /packages/document-outline/lib/document-outline.js:88:12
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at stoppedChangingActivePaneItemCallback (/app.asar/src/pane-container.js:352:36)
```

### Commands

```
     -2:04.4.0 minimap:toggle (input.hidden-input)
     -2:03.6.0 command-palette:toggle (input.hidden-input)
     -2:02.7.0 core:confirm (input.hidden-input)
     -2:02.7.0 document-outline:toggle (input.hidden-input)
     -1:44.5.0 core:save (input.hidden-input)
     -1:40.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:39.8.0 core:backspace (input.hidden-input)
     -1:39.5.0 core:save (input.hidden-input)
     -1:37.4.0 command-palette:toggle (input.hidden-input)
     -1:36.3.0 core:confirm (input.hidden-input)
     -1:36.3.0 document-outline:toggle (input.hidden-input)
     -1:33.7.0 application:add-project-folder (input.hidden-input)
     -1:31.6.0 command-palette:toggle (input.hidden-input)
     -1:30 core:confirm (input.hidden-input)
     -1:30 document-outline:toggle (input.hidden-input)
     -0:01.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
docker 0.7.0 
document-outline 1.4.2 
enhanced-project-folder 0.1.0 
github-atom-light-syntax 0.3.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-cmake 0.3.0 
language-docker 1.1.7 
language-groovy 0.6.0 
language-hcl 0.4.0 
language-latex 1.0.0 
language-lua 0.9.11 
language-nginx 0.7.2 
language-rspec 0.6.1 
language-treetop 0.1.3 
linter 2.1.4 
linter-flake8 2.1.5 
linter-rubocop 2.1.0 
linter-ruby 1.2.5 
linter-shellcheck 1.4.4 
linter-ui-default 1.2.3 
markdown-toc 0.4.2 
minimap 4.27.1 
remove-all-project-folders 0.1.0 
seti-ui 1.7.0 
shebang-set-grammar 0.6.0 
sort-lines 0.14.0 
tree-view-git-status 1.3.1 
```

**Comment by mangecoeur** [comment]
Righto, looks like its not to do with the length, its a bug in handling paragraph titles which was hidden before (I simplified a lot of the code with the latest updates) - basically to do with handling Latex and latex beamer files with the same code.

**Comment by mangecoeur** [comment]
Should be all patched up with the latest version.

**Comment by richard-voss** [comment]
yes, it works again, thanks, that was quick :)
