### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setModel' of null

### ISSUE THREAD

**Issue by LastGreenLeaf** [mangecoeur/document-outline#24]
The package tries to create an outline for the markdown preview every time I focus something in the preview tab. 

Steps to reproduce:
1. Open any markdown file
2. Using markdown-preview-plus generate a preview file
3. Focus anything in generated tab

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Windows 10 Version 1607
**Thrown From**: [document-outline](https://github.com/mangecoeur/document-outline) package 1.4.7

### Stack Trace

Uncaught TypeError: Cannot read property 'setModel' of null

```
At C:\Users\Vitaly\.atom\packages\document-outline\lib\document-outline.js:142

TypeError: Cannot read property 'setModel' of null
    at Object.updateView (/packages/document-outline/lib/document-outline.js:142:14)
    at /packages/document-outline/lib/document-outline.js:133:16
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1392:25
```

### Commands

```
  4x -0:34 core:backspace (input.hidden-input)
     -0:21.4.0 intentions:highlight (input.hidden-input)
     -0:20.9.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:20.7.0 editor:move-to-end-of-word (input.hidden-input)
     -0:20.3.0 core:backspace (input.hidden-input)
     -0:19.9.0 intentions:highlight (input.hidden-input)
     -0:19.7.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -0:18.9.0 core:select-right (input.hidden-input)
     -0:17.4.0 core:move-right (input.hidden-input)
     -0:17.1.0 intentions:highlight (input.hidden-input)
  2x -0:17 editor:move-to-beginning-of-word (input.hidden-input)
     -0:15.2.0 core:backspace (input.hidden-input)
  2x -0:13.2.0 core:select-right (input.hidden-input)
     -0:12.3.0 core:move-left (input.hidden-input)
  2x -0:12.1.0 core:move-right (input.hidden-input)
  2x -0:11.5.0 core:backspace (input.hidden-input)
```

**Comment by mangecoeur** [comment]
I don’t experience this error with markdown preview, but i’ve added a small check which should catch this case anyway.

**Comment by LastGreenLeaf** [comment]
@mangecoeur, Thank you! I was truly annoying)
