### ISSUE TITLE
Document outline broken for Markdown with YAML block

### ISSUE THREAD

**Issue by salim-b** [mangecoeur/document-outline#39]
Some change between v1.6.4 and the newest 1.6.7 (I suspect commit https://github.com/mangecoeur/document-outline/commit/20c0efbe53e146414a34c254edb6ce2cacd4e7a0) broke correct document outlines in Markdown files containing one or more YAML metadata blocks.

Consider the following file:
```
---
documentclass: paper
---

# H1

## H2

...

# H1-2

blabla
```

With v1.6.7 **the document outline contains only `H1-2`**. If you remove either the YAML block or the three `...`  under `H2`, the outline's correct again.

**Comment by mangecoeur** [comment]
Fixed in 1.6.8

**Comment by salim-b** [comment]
> Fixed in 1.6.8

That was fast! Thanks a lot! 🙂

**Comment by salim-b** [comment]
@mangecoeur Well, maybe that was too quick. With v1.6.8 I get
```
Failed to load the document-outline package

/home/salim/.atom/packages/document-outline/lib/markdown-model.js: Invalid regular expression flag (17:12)
```

and the stack trace:
```
SyntaxError: /home/salim/.atom/packages/document-outline/lib/markdown-model.js: Invalid regular expression flag (17:12)
function stripYaml(src, delim) {
  let re = /^---\n(?:\s*)?([\s\S]*)?\n?^(---|\.\.\.)\s*$\n\n?/mU;
  return src.replace(re, '');
}
    at Parser.pp.raise (/opt/atom/resources/app/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.readRegexp (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:564:40)
    at Parser.readToken_slash (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:311:19)
    at Parser.getTokenFromCode (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:488:21)
    at Parser.readToken (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:160:17)
    at Parser.<anonymous> (/opt/atom/resources/app/node_modules/babylon/lib/plugins/jsx/index.js:445:20)
    at Parser.readToken (/opt/atom/resources/app/node_modules/babylon/lib/plugins/flow.js:775:22)
    at Parser.nextToken (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:151:19)
    at Parser.next (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:88:10)
    at Parser.eat (/opt/atom/resources/app/node_modules/babylon/lib/tokenizer/index.js:95:12)
    at Parser.pp.parseVar (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:492:14)
    at Parser.pp.parseVarStatement (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:370:8)
    at Parser.pp.parseStatement (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:99:19)
    at Parser.parseStatement (/opt/atom/resources/app/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseBlock (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:442:21)
    at Parser.pp.parseFunctionBody (/opt/atom/resources/app/node_modules/babylon/lib/parser/expression.js:747:22)
    at Parser.parseFunctionBody (/opt/atom/resources/app/node_modules/babylon/lib/plugins/flow.js:643:20)
    at Parser.pp.parseFunction (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:524:8)
    at Parser.pp.parseFunctionStatement (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:262:15)
    at Parser.pp.parseStatement (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:79:19)
    at Parser.parseStatement (/opt/atom/resources/app/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/opt/atom/resources/app/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/opt/atom/resources/app/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/opt/atom/resources/app/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/opt/atom/resources/app/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/opt/atom/resources/app/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/opt/atom/resources/app/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /opt/atom/resources/app/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/opt/atom/resources/app/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/opt/atom/resources/app/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
```

**Comment by mangecoeur** [comment]
my bad, teach me not to rush things. should be fine now in 1.6.10

**Comment by salim-b** [comment]
@mangecoeur There are still issues present (most probably related to the YAML parsing) when horizontal lines using three `---` are included in the Markdown file.

Consider the following file where the outline is incorrect (`H1-2` is missing) and clicking on those entries which are present takes you to the wrong position in the document. If you remove the horizontal lines, the outline works fine again.

```
# H1-1

---

# H1-2

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

bla

---

## H2-1

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

blup

# H1-3

boing

```

**Comment by mangecoeur** [comment]
thanks for working out the edge cases, should have this fixed now

**Comment by salim-b** [comment]
> thanks for working out the edge cases, should have this fixed now

My Markdown documents are just too complex to not catch the edge cases, I guess 😬 

I got a new error now:
```
Uncaught TypeError: Cannot read property 'index' of null

/home/salim/.atom/packages/document-outline/lib/markdown-model.js:18
```

with stack trace
```
TypeError: Cannot read property 'index' of null
    at stripYaml (/home/salim/.atom/packages/document-outline/lib/markdown-model.js:18:12)
    at MarkdownModel.parse (/home/salim/.atom/packages/document-outline/lib/markdown-model.js:37:12)
    at MarkdownModel.getUpdate (/home/salim/.atom/packages/document-outline/lib/abstract-model.js:47:28)
    at Object.updateView (/home/salim/.atom/packages/document-outline/lib/document-outline.js:148:44)
    at Object.updateCurrentEditor (/home/salim/.atom/packages/document-outline/lib/document-outline.js:133:14)
    at /home/salim/.atom/packages/document-outline/lib/document-outline.js:79:12
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /opt/atom/resources/app/src/workspace.js:550:30
```

**Comment by mangecoeur** [comment]
bleh, ok i solemnly vow not to try to push out quick fixes late at night. I'm pushing a patch for this also, maybe next time i will let things sit on the dev version for. awhile before patching :/
