### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by hussee** [mangecoeur/document-outline#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [document-outline](https://github.com/mangecoeur/document-outline) package 1.6.13

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/huseinvilic/.atom/packages/document-outline/lib/latex-model.js:37

TypeError: Cannot read property '0' of null
    at LatexModel.getRegexData (/packages/document-outline/lib/latex-model.js:37:29)
    at LatexModel._parseLevelFast (/packages/document-outline/lib/abstract-model.js:129:31)
    at LatexModel.parse (/packages/document-outline/lib/abstract-model.js:57:17)
    at LatexModel.getUpdate (/packages/document-outline/lib/abstract-model.js:47:28)
    at Object.updateView (/packages/document-outline/lib/document-outline.js:148:44)
    at /packages/document-outline/lib/document-outline.js:131:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1667:26)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:25.7.0 core:save (input.hidden-input)
     -0:24.4.0 latex:build (input.hidden-input)
     -0:03.3.0 docblockr:parse-tab (input.hidden-input)
     -0:03.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:03.3.0 snippets:expand (input.hidden-input)
     -0:03.2.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-clock 0.1.15 
busy-signal 1.4.3 
docblockr 0.11.0 
document-outline 1.6.13 
git-plus 7.9.3 
git-time-machine 1.5.9 
hey-pane 1.0.0 
Hydrogen 1.23.0 
intentions 1.1.5 
language-latex 1.1.1 
language-tex 0.4.0 
latex 0.48.0 
latexer 0.3.0 
pdf-view 0.59.0 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
tab-switcher 1.5.6 
```

**Comment by mangecoeur** [comment]
closing in favour of #48
