### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by lgarcin** [mangecoeur/document-outline#48]
[Enter steps to reproduce:]

1. Open rst file

**Atom**: 1.21.0 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [document-outline](https://github.com/mangecoeur/document-outline) package 1.6.13

### Stack Trace

Uncaught TypeError: Cannot read property '2' of null

```
At C:\Users\laure\.atom\packages\document-outline\lib\rst-model.js:14

TypeError: Cannot read property '2' of null
    at ReStructuredTextModel.getRegexData (/packages/document-outline/lib/rst-model.js:14:23)
    at ReStructuredTextModel._parseLevelFast (/packages/document-outline/lib/abstract-model.js:129:31)
    at ReStructuredTextModel.parse (/packages/document-outline/lib/abstract-model.js:57:17)
    at ReStructuredTextModel.getUpdate (/packages/document-outline/lib/abstract-model.js:47:28)
    at Object.updateView (/packages/document-outline/lib/document-outline.js:148:44)
    at /packages/document-outline/lib/document-outline.js:131:16
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1667:26)
    at later (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
 12x -0:57.9.0 core:backspace (input.hidden-input)
     -0:55.4.0 core:confirm (input.hidden-input)
     -0:40.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:40.8.0 editor:newline (input.hidden-input)
  5x -0:35.8.0 core:backspace (input.hidden-input)
     -0:33.1.0 intentions:highlight (input.hidden-input)
     -0:32.6.0 core:save (input.hidden-input)
     -0:21.7.0 core:backspace (input.hidden-input)
     -0:18.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:18.3.0 editor:newline (input.hidden-input)
  2x -0:11.2.0 core:move-up (input.hidden-input)
     -0:10.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:10.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:10.3.0 editor:newline (input.hidden-input)
     -0:10 core:move-up (input.hidden-input)
     -0:02.8.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
atom-ternjs 0.18.3 
autocomplete-glsl 0.2.3 
autocomplete-haskell 1.0.1 
autocomplete-modules 1.7.2 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
document-outline 1.6.13 
editorconfig 2.2.2 
elm-format 3.0.0 
elmjutsu 7.0.2 
es6-javascript 1.0.0 
file-icons 2.1.13 
haskell-ghc-mod 2.1.1 
highlight-selected 0.13.1 
Hydrogen 1.23.0 
hyperclick 0.1.5 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.3 
ide-haskell-repl 0.7.3 
imdone-atom 2.2.7 
indent-detective 0.1.1 
ink 0.7.7 
intentions 1.1.5 
ionide-fake 1.2.2 
ionide-fsharp 1.9.3 
ionide-fsi 2.1.3 
ionide-installer 1.4.0 
ionide-paket undefined 
ionide-webview 1.0.3 
javascript-snippets 1.2.1 
julia-client 0.6.4 
kite 0.47.1 
language-babel 2.75.1 
language-elm 1.5.0 
language-gfm-enhanced 0.92.0 
language-glsl 2.0.2 
language-haskell 1.14.3 
language-julia 0.12.0 
language-latex 1.1.1 
language-liquid 0.6.0 
language-lua 0.9.11 
language-markdown 0.25.1 
language-restructuredtext 1.1.0 
language-weave 0.4.2 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latextools 0.8.5 
linter 2.2.0 
linter-elm-make 0.26.2 
linter-eslint 8.3.2 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.7.2 
minimap 4.29.7 
pdf-view 0.59.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
preview-inline 1.4.7 
rst-preview-pandoc 0.1.12 
script 3.17.1 
todo-show 2.1.0 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.3.0 
uber-juno 0.1.2 
windows-build-tools 1.0.0 
```

**Comment by mangecoeur** [comment]
can you post an example of the file that causes this issue?

**Comment by lgarcin** [comment]
My desciption of the error was wrong. Here are the steps to reproduce to get the error.

1. Create a blank rst file.

2. Type a first row of `=` signs with a title.

```
====
Test
```

At that moment, everything is still fine.

3. Type a second row of `=` signs.

```
====
Test
====
```
I get an error each time I type `=`.



But when I close and reopen the same file, I don't get any error when I modify the rows of `=` signs.
